solution
mate-academy/js_sliding-tree-DOM pull request #311
Opened 2021-03-10 16:23 UTC by yyashnyi

[DEMO LINK](https://yashnyi.github.io/js_sliding-tree-DOM/)

2021-03-11 07:37 UTC, ivan-panchenko1992 approved these changes
Very clever

2021-03-11 07:49 UTC, solaryasha requested changes

2021-03-11 07:49 UTC, solaryasha commented on src/scripts/main.js
> +  );
Можеш ще застосувати replaceWith, але це необов'язково

2021-03-11 07:49 UTC, solaryasha commented on src/scripts/main.js
> +  if (e.target.tagName.toLowerCase() === 'span') {
Краще додай до спана клас і шукай по класу найближчий

2021-03-12 09:57 UTC, solaryasha approved these changes

2021-03-12 09:57 UTC, solaryasha commented on src/scripts/main.js
> +  element.firstChild.classList.add('span');
Оригінально))

2025-09-01 20:49 UTC, closed without merging