Solution
mate-academy/js_sliding-tree-DOM pull request #502
Opened 2022-07-07 09:19 UTC by BudnikOleksii

- [DEMO LINK](https://BudnikOleksii.github.io/js_sliding-tree-DOM/)

2022-07-07 09:40 UTC, solaryasha requested changes

2022-07-07 09:40 UTC, solaryasha commented on src/scripts/main.js
> +list.addEventListener('click', (e) => {
Avoid using one-letter variable namings.

2022-07-07 09:40 UTC, solaryasha commented on src/scripts/main.js
> +  if (target.tagName === 'SPAN') {
It could be better to detect element by some another descriptor (like, custom data-attribute)

2022-07-11 09:07 UTC, ivan-kadykalo approved these changes
🔥

2025-05-30 11:53 UTC, closed without merging